languaje: node_js
node_js:
  - 10.16.3
cache: npm
install: 
  - npm ci
script:
  - npm run test
  - npm run bundle
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master