languaje: node_js
node_js:
  - 10.16.3
cache: npm
install: 
  - npm ci
script:
  - npm run test
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  ithub-token: $GITHUB_TOKEN
  on:
    branch: gh-pages